### ISSUE TITLE
Where does it save the redirects?

### ISSUE THREAD

**Issue by psntr** [bnomei/kirby3-redirects#15]
Hi,

I was wondering where do this plugin save the redirections?

**Comment by bnomei** [comment]
the structure is defined using the blueprint section.

**site/blueprints/site.yml**
```yml
sections:
  # ...other sections
  redirects:
    extends: plugin-redirects3xx
```

by default it loads from that structure as defined in the `bnomei.redirects.map` setting callback.

but since its a callback you could overwrite it to just load from a json/yaml file you manage yourself. thats why the php api like `site()->appendRedirects(...)` exists.
