### ISSUE TITLE
Fetching Codes

### ISSUE THREAD

**Issue by nilshoerrmann** [bnomei/kirby3-redirects#4]
Fetching response codes makes the panel unresponsive with a growing number of redirects. It's works with a few entries in the redirects fields but we have a list of 160 redirects and the panel hasn't finished loading after 30 seconds.

**Comment by bnomei** [comment]
oh. will fix that asap.

**Comment by bnomei** [comment]
i will add a cache to the generation of the codes but the api request might still be too slow in your case. thats why i added a hardcoded 3xx section. you can use it with 

**site.yml**
```yaml
sections:
  # ...other sections
  redirects:
    extends: plugin-redirects3xx
```

**Comment by nilshoerrmann** [comment]
This new section loads quickly but it doesn't show existing codes in the panel and stores the full value for new items (e. g. `301: Moved Permanently` instead of `301`):

![bildschirmfoto am 2019-01-14 um 20 18 03](https://user-images.githubusercontent.com/25466/51135227-c5aa8500-1839-11e9-90ee-07cb20ec43d8.png)


```yaml
Redirects: 

- 
  fromuri: /building/ahmic.html
  touri: projects/ahmic
  code: '301: Moved Permanently'
```
